name: Validate generated-dockerfiles

on: pull_request

jobs:
  update-dockerfiles:
    name: Dockerfiles up-to-date
    runs-on: ubuntu-latest
    container: python:3.8
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate new Dockerfiles
        run: |
          pip install -r requirements.txt
          ./generate_dockerfiles.py
      - name: Check diffs
        run: git diff --exit-code --quiet
